// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF4166kJgYhANz2yCS5QSKV-YVY4qJuL0',
    appId: '1:633244012626:web:27d72ad18beb552eaecf8b',
    messagingSenderId: '633244012626',
    projectId: 'dicoding-chatting-fa337',
    authDomain: 'dicoding-chatting-fa337.firebaseapp.com',
    storageBucket: 'dicoding-chatting-fa337.appspot.com',
    measurementId: 'G-XKGT6SSCCJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQHmICNA-KwcvqM8l7Km2PKcJneovT0d8',
    appId: '1:633244012626:android:7b338ef094dda39caecf8b',
    messagingSenderId: '633244012626',
    projectId: 'dicoding-chatting-fa337',
    storageBucket: 'dicoding-chatting-fa337.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwmoR0fdRUzeroa1pf8WG6wJPQlvqwrP4',
    appId: '1:633244012626:ios:344d323059a9d223aecf8b',
    messagingSenderId: '633244012626',
    projectId: 'dicoding-chatting-fa337',
    storageBucket: 'dicoding-chatting-fa337.appspot.com',
    iosClientId: '633244012626-d806u55fumofkao904d8rgp5tu2crd7e.apps.googleusercontent.com',
    iosBundleId: 'com.dicoding.dicodingChatting',
  );
}
