// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa0_adnlp9iFIX0B2LU7XHm4ty4IVE60o',
    appId: '1:1067487787603:web:799f47ae5055e864fbe4a6',
    messagingSenderId: '1067487787603',
    projectId: 'dummy-project-db135',
    authDomain: 'dummy-project-db135.firebaseapp.com',
    storageBucket: 'dummy-project-db135.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABz3cVDKxboQ7H_4T8A_jO08uRlVAQNw0',
    appId: '1:1067487787603:android:fa5b8b14ffb5f771fbe4a6',
    messagingSenderId: '1067487787603',
    projectId: 'dummy-project-db135',
    storageBucket: 'dummy-project-db135.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjjQ-UFX3BER5Cnv5c9Yyrr-jrYAiLKsU',
    appId: '1:1067487787603:ios:b2063a7f7cdeb7e8fbe4a6',
    messagingSenderId: '1067487787603',
    projectId: 'dummy-project-db135',
    storageBucket: 'dummy-project-db135.appspot.com',
    iosClientId: '1067487787603-20v13ep6kfpmpbnj91h7lupfh5mf5bh8.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramExampleCreate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjjQ-UFX3BER5Cnv5c9Yyrr-jrYAiLKsU',
    appId: '1:1067487787603:ios:b2063a7f7cdeb7e8fbe4a6',
    messagingSenderId: '1067487787603',
    projectId: 'dummy-project-db135',
    storageBucket: 'dummy-project-db135.appspot.com',
    iosClientId: '1067487787603-20v13ep6kfpmpbnj91h7lupfh5mf5bh8.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramExampleCreate',
  );
}
